FROM public.ecr.aws/lambda/python:$python_version

RUN yum install -y java-1.8.0-openjdk-devel-1.8.0.302.b08-0.amzn2.0.1

COPY lambda_function.py ./
COPY requirements.txt ./

RUN pip install -r ./requirements.txt

CMD ["lambda_function.lambda_handler"]