FROM amazoncorretto:8

RUN yum -y update
RUN yum -y install yum-utils
RUN yum -y groupinstall development

RUN yum -y install python3 python3-dev python3-pip python3-virtualenv

ENV PYSPARK_DRIVER_PYTHON python3
ENV PYSPARK_PYTHON python3

RUN pip3 install --upgrade pip

RUN pip3 install --target ${FUNCTION_DIR} awslambdaric
ENTRYPOINT ["/usr/local/bin/python3", "-m", "awslambdaric"]

COPY lambda_function.py ./
COPY requirements.txt ./

RUN pip install -r ./requirements.txt

CMD ["lambda_function.lambda_handler"]