version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-deps
      - python/tests
workflows:
  main:
    jobs:
      - build-and-test
