version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 517169013426.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - sam build
      - sam package --output-template-file packaged-template.yml --image-repository 517169013426.dkr.ecr.us-east-1.amazonaws.com/modfunction946893-repository
      - sam deploy --template-file packaged-template.yml --stack-name modfunction946893-stack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --region us-east-1 --image-repository 517169013426.dkr.ecr.us-east-1.amazonaws.com/modfunction946893-repository
